require './app/models/comedian.rb'

bernie_mac = Comedian.create(name: "Bernie Mac", age: 65, city: "Chicago")
sarah_silverman = Comedian.create(name: "Sarah Silverman", age: 48, city: "Bedford")
dave_chappelle = Comedian.create(name: "Dave Chappelle", age: 45, city: "D.C.")
steve_martin = Comedian.create(name: "Steve Martin", age: 73, city: "Waco")
kevin_hart = Comedian.create(name: "Kevin Hart", age: 39, city: "Philly")
ellen_degeneres = Comedian.create(name: "Ellen Degeneres", age: 61, city: "Metairie")
aziz_ansari = Comedian.create(name: "Aziz Ansari", age: 34, city: "Columbia")
tiny_fey = Comedian.create(name: "Tina Fey", age: 34, city: "Upper Darby")
amy_poehler = Comedian.create(name: "Amy Poehler", age: 47, city: "Newton")
kristen_wiig = Comedian.create(name: "Kristen Wiig", age: 34, city: "Albany")

bernie_sp1 = bernie_mac.specials.create(name: "The Original Kings of Comedy", length: 115, url: "https://www.imdb.com/title/tt0236388/mediaviewer/rm4271217664")
bernie_sp2 = bernie_mac.specials.create(name: "A Tribute to Bernie Mac", length: 60, url: "https://www.imdb.com/title/tt1987585/mediaviewer/rm2655441408")
sarah_sp1 = sarah_silverman.specials.create(name: "A Speck of Dusk", length: 71, url: "https://www.imdb.com/title/tt6948354/mediaviewer/rm1197746944")
sarah_sp2 = sarah_silverman.specials.create(name: "We Are Miracles", length: 53, url: "https://www.imdb.com/title/tt2883224/mediaviewer/rm2300649728")
dave_sp1 = dave_chappelle.specials.create(name: "Equanimity", length: 60, url: "https://www.imdb.com/title/tt7806998/mediaviewer/rm957699072")
dave_sp2 = dave_chappelle.specials.create(name: "The Bird Revelation", length: 49, url: "https://www.imdb.com/title/tt7807000/mediaviewer/rm2503955200")
steve_sp1 = steve_martin.specials.create(name: "Comedy is Not Pretty", length: 60, url: "https://www.imdb.com/title/tt0336189/mediaviewer/rm3766473216")
steve_sp2 = steve_martin.specials.create(name: )
kevin_sp1 = kevin_hart.specials.create(hash)
kevin_sp2 = kevin_hart.specials.create(hash)
ellen_sp1 = ellen_degeneres.specials.create(hash)
ellen_sp2 = ellen_degeneres.specials.create(hash)
aziz_sp1 = aziz_ansari.specials.create(hash)
aziz_sp2 = aziz_ansari.specials.create(hash)
tina_sp1 = tiny_fey.specials.create(hash)
tina_sp2 = tiny_fey.specials.create(hash)
amy_sp1 = amy_poehler.specials.create(hash)
amy_sp2 = amy_poehler.specials.create(hash)
kristen_sp1 = kristen_wiig.specials.create(hash)
kristen_sp2 = kristen_wiig.specials.create(hash)
# Puts "added #{comedian.specials.count} to #{comedian.name}"
