require File.expand_path('../../config/environment.rb', __FILE__)

bernie_mac = Comedian.create(name: "Bernie Mac", age: 65, city: "Chicago")
sarah_silverman = Comedian.create(name: "Sarah Silverman", age: 48, city: "Bedford")
dave_chappelle = Comedian.create(name: "Dave Chappelle", age: 45, city: "D.C.")
steve_martin = Comedian.create(name: "Steve Martin", age: 73, city: "Waco")
kevin_hart = Comedian.create(name: "Kevin Hart", age: 39, city: "Philly")
ellen_degeneres = Comedian.create(name: "Ellen Degeneres", age: 61, city: "Metairie")
aziz_ansari = Comedian.create(name: "Aziz Ansari", age: 34, city: "Columbia")
wanda_sykes = Comedian.create(name: "Wanda Sykes", age: 54, city: "Portsmouth")
amy_schumer = Comedian.create(name: "Amy Schumer", age: 34, city: "Upper East Side")
george_carlin = Comedian.create(name: "George Carlin", age: 81, city: "Manhattan")

bernie_sp1 = bernie_mac.specials.create(name: "The Original Kings of Comedy", length: 115, url: "https://m.media-amazon.com/images/M/MV5BMTk4NzExMTE2OF5BMl5BanBnXkFtZTcwNDIyNzEyMQ@@._V1_.jpg")
bernie_sp2 = bernie_mac.specials.create(name: "A Tribute to Bernie Mac", length: 60, url: "https://m.media-amazon.com/images/M/MV5BMTU4NzQ0NjQ1Ml5BMl5BanBnXkFtZTgwOTAwNjA2MDE@._V1_.jpg")
sarah_sp1 = sarah_silverman.specials.create(name: "A Speck of Dusk", length: 71, url: "https://m.media-amazon.com/images/M/MV5BMjYwYjhjM2EtYjgwYS00YjkyLTllMjQtZGM1ZmFkMTQ1YmFmXkEyXkFqcGdeQXVyMzUwMjc0NTU@._V1_.jpg")
sarah_sp2 = sarah_silverman.specials.create(name: "We Are Miracles", length: 53, url: "https://m.media-amazon.com/images/M/MV5BODU5MWI2YWEtNTQ3Ny00OWQ3LThkNTUtYzdiNDVjNDczM2NiXkEyXkFqcGdeQXVyMTk3NDAwMzI@._V1_SY1000_SX675_AL_.jpg")
dave_sp1 = dave_chappelle.specials.create(name: "Equanimity", length: 60, url: "https://m.media-amazon.com/images/M/MV5BODJkMTAxNmYtZDg4OS00NzA2LTlmZTUtMDc2MjIwMzE4ZDMxXkEyXkFqcGdeQXVyMTk3NDAwMzI@._V1_.jpg")
dave_sp2 = dave_chappelle.specials.create(name: "The Bird Revelation", length: 49, url: "https://m.media-amazon.com/images/M/MV5BNGYzOTE0YzEtMjc5NC00MTg2LTk2MDAtMzJlMjM1NTU1MjcwXkEyXkFqcGdeQXVyMTk2ODU0OTM@._V1_.jpg")
steve_sp1 = steve_martin.specials.create(name: "Comedy is Not Pretty", length: 60, url: "https://m.media-amazon.com/images/M/MV5BMjEzMTQ1OTMwOV5BMl5BanBnXkFtZTgwNjk3OTk1MDE@._V1_.jpg")
steve_sp2 = steve_martin.specials.create(name: "
Steve Martin and Martin Short: An Evening You Will Forget for the Rest of Your Life", length: 74, url: "https://m.media-amazon.com/images/M/MV5BMTI5ZjQzNzktYTk2OS00ZWFiLWFlMjctNGZjMTU3NjAyMjEyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg")
kevin_sp1 = kevin_hart.specials.create(name: "I'm a Grown Little Man", length: 73, url: "https://m.media-amazon.com/images/M/MV5BMjI4MTYwNTUzMF5BMl5BanBnXkFtZTcwODk1Mjk3Mw@@._V1_.jpg")
kevin_sp2 = kevin_hart.specials.create(name: "Laugh At My Pain", length: 89, url: "https://m.media-amazon.com/images/M/MV5BMjI4NjA5NTI0OV5BMl5BanBnXkFtZTcwMTU0MzI1Ng@@._V1_.jpg")
ellen_sp1 = ellen_degeneres.specials.create(name: "Here and Now", length: 60, url: "https://m.media-amazon.com/images/M/MV5BMTgyNzgxMDA5MF5BMl5BanBnXkFtZTcwMTI1NTQyMQ@@._V1_.jpg")
ellen_sp2 = ellen_degeneres.specials.create(name: "One Night Stand", length: 26, url: "https://m.media-amazon.com/images/M/MV5BZTQyNGYwNTctMDkzYi00Mzk5LTlmYjktOWY3YmNjNDc0YmJkXkEyXkFqcGdeQXVyNTM3MDMyMDQ@._V1_.jpg")
aziz_sp1 = aziz_ansari.specials.create(name: "Dangerously Delicious", length: 61, url: "https://m.media-amazon.com/images/M/MV5BYzYzNzlhYTEtYTdkNS00NDdiLWE1N2MtM2ZlOTQzMjU5OTg5XkEyXkFqcGdeQXVyMTIxMDUyOTI@._V1_.jpg")
aziz_sp2 = aziz_ansari.specials.create(name: "Buried Alive", length: 80, url: "https://m.media-amazon.com/images/M/MV5BNzAyNTYyODI5Nl5BMl5BanBnXkFtZTgwMzkwMzY1MDE@._V1_SY1000_CR0,0,679,1000_AL_.jpg")
wanda_sp1 = wanda_sykes.specials.create(name: "I'ma Be Me", length: 87, url: "https://m.media-amazon.com/images/M/MV5BOTAxODQ3NzQxOV5BMl5BanBnXkFtZTcwNDIwOTY4Mg@@._V1_SY1000_CR0,0,666,1000_AL_.jpg")
wanda_sp2 = wanda_sykes.specials.create(name: "Sick and Tired", length: 70, url: "https://m.media-amazon.com/images/M/MV5BMTg4NjcxMDY1N15BMl5BanBnXkFtZTcwNDYxOTUzMQ@@._V1_.jpg")
amy_sp1 = amy_schumer.specials.create(name: "The Leather Special", length: 57, url: "https://m.media-amazon.com/images/M/MV5BMGMxYWY1MTktZDFlNC00YjdjLTk5MGMtODEwNTZiY2MxZjk1XkEyXkFqcGdeQXVyNTI3NjIyMjI@._V1_.jpg")
amy_sp2 = amy_schumer.specials.create(name: "Mostly Sex Stuff", length: 61, url: "https://m.media-amazon.com/images/M/MV5BMTQxOTI2ODgxNF5BMl5BanBnXkFtZTgwMzc0NDAxMzE@._V1_.jpg")
george_sp1 = george_carlin.specials.create(name: "You Are Alll Diseased", length: 65, url: "https://m.media-amazon.com/images/M/MV5BMTIxMjA3OTYwNF5BMl5BanBnXkFtZTcwMTU5OTcxMQ@@._V1_.jpg")
george_sp2 = george_carlin.specials.create(name: "Life is Worth Losing", length: 75, url: "https://m.media-amazon.com/images/M/MV5BMTI2ODk4OTg1NF5BMl5BanBnXkFtZTcwNjM5MzU0MQ@@._V1_.jpg")
